### ISSUE TITLE
Tests depending upon custom config cannot be executed concurrently

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/kap-plugin-mock-context#1]
Because I use `Conf` right [here](https://github.com/SamVerschueren/kap-plugin-mock-context/blob/master/index.js#L23) without a custom [configName](https://github.com/sindresorhus/conf#configname) we are not able to execute tests concurrently at the moment because the config JSON files are interfering. How should I solve this? Use [cwd](https://github.com/sindresorhus/conf#cwd) together with `tempy` in order to randomly create a new JSON location?

// @sindresorhus @kevva

**Comment by kevva** [comment]
Do we need to write to disk at all? I guess you're using `Conf` to keep it consistent with `kap` use of `electron-config`?

**Comment by SamVerschueren** [comment]
Yes, I wanted it to have the same API which is why I used Conf. Same goes for the request method. It forwards it to got, like the real context, but it is never called. The reason for that is that we stub that method in kap-plugin-test and a stub does not call it's original method. So I guess we can remove that one as well and drop the entire dependency.
